In [65]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [66]:
from sklearn.datasets import fetch_openml
boston = fetch_openml(name= "boston",version=1,as_frame = True)
boston

{'data':         CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
 0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
 1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
 2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
 3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
 4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
 ..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
 501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
 502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
 503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
 504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
 505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

 [506 rows x 13 columns],
 'target': 0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ...
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
 'frame':         CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
 0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
 1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
 2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
 3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
 4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
 ..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
 501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
 502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
 503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
 504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
 505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

 [506 rows x 14 columns],
 'categories': None,
 'feature_names': ['CRIM',
  'ZN',
  'INDUS',
  'CHAS',
  'NOX',
  'RM',
  'AGE',
  'DIS',
  'RAD',
  'TAX',
  'PTRATIO',
  'B',
  'LSTAT'],
 'target_names': ['MEDV'],
 'DESCR': "**Author**:   \n**Source**: Unknown - Date unknown  \n**Please cite**:   \n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\nVariables in order:\nCRIM     per capita crime rate by town\nZN       proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS    proportion of non-retail business acres per town\nCHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\nNOX      nitric oxides concentration (parts per 10 million)\nRM       average number of rooms per dwelling\nAGE      proportion of owner-occupied units built prior to 1940\nDIS      weighted distances to five Boston employment centres\nRAD      index of accessibility to radial highways\nTAX      full-value property-tax rate per $10,000\nPTRATIO  pupil-teacher ratio by town\nB        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT    % lower status of the population\nMEDV     Median value of owner-occupied homes in $1000's\n\n\nInformation about the dataset\nCLASSTYPE: numeric\nCLASSINDEX: last\n\nDownloaded from openml.org.",
 'details': {'id': '531',
  'name': 'boston',
  'version': '1',
  'description_version': '1',
  'format': 'ARFF',
  'creator': ['D. and Rubinfeld', "D.L. 'Hedonic"],
  'collection_date': '1978',
  'upload_date': '2014-09-29T00:08:07',
  'language': 'English',
  'licence': 'Public',
  'url': 'https://openml.org/data/v1/download/52643/boston.arff',
  'parquet_url': 'https://data.openml.org/datasets/0000/0531/dataset_531.pq',
  'file_id': '52643',
  'default_target_attribute': 'MEDV',
  'tag': ['Data Science',
   'Housing Economics',
   'Kaggle',
   'OpenML-Reg19',
   'study_130',
   'Urban Studies'],
  'visibility': 'public',
  'status': 'active',
  'processing_date': '2020-11-20 20:16:37',
  'md5_checksum': 'cdd361fb886627eaa80c92f90d0610cc'},
 'url': 'https://www.openml.org/d/531'}

In [67]:
df= boston.frame
print(df.head())

      CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0  0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1  0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2  0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3  0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4  0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2

[5 rows x 14 columns]

In [68]:
df

        CRIM    ZN  INDUS CHAS    NOX  ...    TAX  PTRATIO       B LSTAT  MEDV
0    0.00632  18.0   2.31    0  0.538  ...  296.0     15.3  396.90  4.98  24.0
1    0.02731   0.0   7.07    0  0.469  ...  242.0     17.8  396.90  9.14  21.6
2    0.02729   0.0   7.07    0  0.469  ...  242.0     17.8  392.83  4.03  34.7
3    0.03237   0.0   2.18    0  0.458  ...  222.0     18.7  394.63  2.94  33.4
4    0.06905   0.0   2.18    0  0.458  ...  222.0     18.7  396.90  5.33  36.2
..       ...   ...    ...  ...    ...  ...    ...      ...     ...   ...   ...
501  0.06263   0.0  11.93    0  0.573  ...  273.0     21.0  391.99  9.67  22.4
502  0.04527   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  9.08  20.6
503  0.06076   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  5.64  23.9
504  0.10959   0.0  11.93    0  0.573  ...  273.0     21.0  393.45  6.48  22.0
505  0.04741   0.0  11.93    0  0.573  ...  273.0     21.0  396.90  7.88  11.9

[506 rows x 14 columns]

In [69]:
#split the dependent and independent data frame
x = df.drop("MEDV",axis =1 ) #drop the column containing the targets 
y = boston["target"]

x

        CRIM    ZN  INDUS CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0    0.00632  18.0   2.31    0  0.538  ...    1  296.0     15.3  396.90   4.98
1    0.02731   0.0   7.07    0  0.469  ...    2  242.0     17.8  396.90   9.14
2    0.02729   0.0   7.07    0  0.469  ...    2  242.0     17.8  392.83   4.03
3    0.03237   0.0   2.18    0  0.458  ...    3  222.0     18.7  394.63   2.94
4    0.06905   0.0   2.18    0  0.458  ...    3  222.0     18.7  396.90   5.33
..       ...   ...    ...  ...    ...  ...  ...    ...      ...     ...    ...
501  0.06263   0.0  11.93    0  0.573  ...    1  273.0     21.0  391.99   9.67
502  0.04527   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   9.08
503  0.06076   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   5.64
504  0.10959   0.0  11.93    0  0.573  ...    1  273.0     21.0  393.45   6.48
505  0.04741   0.0  11.93    0  0.573  ...    1  273.0     21.0  396.90   7.88

[506 rows x 13 columns]

In [70]:
#make the test train split
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test = tts(x,y,random_state=80,test_size= 0.23)

Applying the decision tree regression model without cross validations

In [71]:
from sklearn.tree import DecisionTreeRegressor

In [72]:
model = DecisionTreeRegressor()
model.fit(x_train,y_train)

DecisionTreeRegressor()

In [73]:
y_pred = model.predict(x_test)

In [74]:
from sklearn.metrics import mean_squared_error,r2_score

mean = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print( f"MSE : {mean}")
print( f"R2 score : {r2}")

MSE : 14.669059829059833
R2 score : 0.7829260886906653

    Doing the same thing by doing hyperparameter tuning using CrossValidation of training data

In [75]:
from sklearn.model_selection import GridSearchCV

In [76]:
parameters = {
    "criterion" : ["squared_error" , "friedman_mse", "absolute_error","poisson"],
    "splitter" : ["best","random"],
    "max_depth" :[1,2,3,4,5,6,7,8,9,10,11,12],
    "max_features" :["sqrt", "log2",None]
}

In [77]:
#get the models 
treemodel = DecisionTreeRegressor()
gridModel = GridSearchCV(treemodel,
                         param_grid=parameters,
                         cv = 5, 
                         scoring= "neg_mean_squared_error")

In [78]:
#train the models
gridModel.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             scoring='neg_mean_squared_error')

In [79]:
gridModel.best_params_

{'criterion': 'poisson',
 'max_depth': 5,
 'max_features': None,
 'splitter': 'best'}

In [80]:
y_pred = gridModel.predict(x_test)

In [81]:
from sklearn.metrics import mean_squared_error,r2_score

mean = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
print( f"MSE : {mean}")
print( f"R2 score : {r2}")

MSE : 12.135363229457997
R2 score : 0.8204199320150457